SERVICE_PORT_LDAP="389"
SERVICE_PORT_SLDAP="686"
SERVICE_PASSWORD_LDAP="$(service::get_password ldap)"

LDAP_ORGANIZATION="${ORG_NAME}"
LDAP_DOMAIN="${ORG_DOMAIN}"

LDAP_BASE_RDN="dc=${ORG_DOMAIN//./,dc=}"
